### ISSUE TITLE
Question about training chinese speech diarization model

### ISSUE THREAD

**Issue by incomingflyingbrick** [wq2012/awesome-diarization#18]
It was memtioned in your paper that google used 36M utterance and 18K speaker to train the model. If I want to training a chinese version of the speech diazarition model. How much data do I need for that? 
Thank you.

**Comment by wq2012** [comment]
That really depends on your speaker embedding model, the type of data (domain, acoustic condition, etc.), whether you pretrain your model, and how consistency it is between your training data and your target domain.

But in general, we found that for industry applications, 10K training speakers is often a bar.
