### ISSUE TITLE
Multi-scale Speaker Diarization with Dynamic Scale Weighting

### ISSUE THREAD

**Issue by v-nhandt21** [wq2012/awesome-diarization#30]
Do you think the method from Nvidia in 2022 is impact: 

Multi-scale Speaker Diarization with Dynamic Scale Weighting : https://arxiv.org/pdf/2203.15974.pdf 

And 

TitaNet: Neural Model for speaker representation with 1D Depth-wise separable convolutions and global context

I found it in the leaderboard of Paper with code

**Comment by wq2012** [comment]
Yeah these are both great work. Feel free to add them to the list of papers in a PR.
