### ISSUE TITLE
Speaker diarization blogpost etc

### ISSUE THREAD

**Issue by judyfong** [wq2012/awesome-diarization#36]
Hello, 

I worked on speaker diarization during about 2019-2022. This is the main result of my work: https://github.com/cadia-lvl/kaldi-speaker-diarization/tree/238ecb56ba7563bc09aa6b143c0c6315eca0c0c5

but I’m not sure where in the repo to fit it in, also I was writing a blogpost and have many other tools and resources I made and worked on for diarization. I wasn’t sure where to place them in the repo. But I think the blogpost could clarify it all. Initially my conclusions after using the JHU recipes, were the same as the authors, but after studying linguistics in the intervening years I have a different viewpoint of the problems. So do you accept blogposts as resources and if so under what section? i can show you a draft to help you figure it out if that would help.

**Comment by wq2012** [comment]
Any code should go to the "Software" section. You can pick a subsection based on what purpose the code is for.

Any online articles should go to the "Tech blogs" section.

**Comment by judyfong** [comment]
Awesome! And I guess in the PR you can say whether you agree with the location or think another spot is better. OK. Understood.
